CoreProject/Controllers/RegisterController.cs
using BussinessLayer.Concrete;
using BussinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc;

namespace CoreProject.Controllers
{
	public class RegisterController : Controller
	{
		WriterManager manager = new WriterManager(new EFWriterRepository());
		WriterValidator validator = new WriterValidator();
		[HttpGet]
		public IActionResult Index()
		{
			return View();
		}
		[HttpPost]
		public IActionResult Index(Writer writer)
		{
			writer.Status = true;
			writer.About = "Kendisi bir yazardır.";
			writer.Image = "/coreblogtema/web/images/t3.jpg";
			
			ValidationResult validationResult = validator.Validate(writer);

			if (validationResult.IsValid)
			{
				manager.Add(writer);
				return RedirectToAction("Index", "Blog");
			}else
			{
				foreach (var item in validationResult.Errors)
				{
					ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
				}
				return View();
			}

			
            
		}
	}
}

CoreProject/Views/Register/Index.cshtml
@model EntityLayer.Concrete.Writer
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/CoreLayout.cshtml";
}
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/jquery/dist/jquery.js"></script>

<section class="main-content-w3layouts-agileits">
	<div class="container">
		<h3 class="tittle">Kayıt Ol</h3>
		<div class="inner-sec">
			<div class="login p-5 bg-light mx-auto mw-100">
				@using(Html.BeginForm("Index","Register", FormMethod.Post))
				{
					<form action="#" method="post">
					<div class="form-row">
						<div class="col-md-6 mb-3">
							<label for="validationCustom01">Adın</label>

								@*<input type="text" class="form-control" id="validationDefault01" name="Name" placeholder="" required="">*@
							@Html.TextBoxFor(x=> x.Name, new {@class="form-control"})
							@Html.ValidationMessageFor(x=> x.Name,"", new {@class="text-danger"})
						</div>
						<div class="col-md-6 mb-3">
							<label for="validationCustom02">E-Posta Adresin</label>
							@*<input type="email" class="form-control" id="validationDefault02" name="Email" placeholder="" required="">*@
								@Html.TextBoxFor(x=> x.Email, new {@class="form-control"})
								@Html.ValidationMessageFor(x=> x.Email,"", new {@class="text-danger"})
						</div>
					</div>
					<div class="form-row">
						<div class="form-group col-md-6">
							<label for="exampleInputPassword1 mb-2">Şifren</label>
							@*<input type="password" class="form-control" id="password1" placeholder="" name="Password" required="">*@
								@Html.TextBoxFor(x=> x.Password, new {@class="form-control"})
								@Html.ValidationMessageFor(x=> x.Password,"", new {@class="text-danger"})
						</div>
						<div class="form-group col-md-6">
							<label for="exampleInputPassword2 mb-2">Resmin</label>
								@*<input type="text" class="form-control" id="image" name="Image" placeholder="" required="">*@
								@Html.TextBoxFor(x=> x.Image, new {@class="form-control"})
								@Html.ValidationMessageFor(x=> x.Image,"", new {@class="text-danger"})
						</div>

					</div>
					<button type="submit" class="btn btn-primary submit mb-4">Kayıt Ol</button>
					<p>
						<a href="#" id="btn1">Kayıt Ol butonuna tıklayarak, Koşullar ve Şartları kabul ediyorum.</a>
					</p>
				</form>
				}
				

			</div>
		</div>
	</div>
	<script>
		$('#btn1').click(function(){
			swal("Koşullar ve Şartlar", "Sitemizde verdiğimiz e-posta adresi üzerinden bilgi ve haber e-postaları spam ölçüsüne varmadan gönderilecektir. Eğer e-posta bülteninden çıkmak isterseniz e-posta ileti dizisini durdurabilirsiniz. Şifre ve e-posta adresiniz şifrelenmiş formatta kimsenin görmeyeceği şekilde saklanmaktadır.");
		});
	</script>
</section>